name: Build and upload

# test
on:
  workflow_call:
jobs:
  build_upload:
    name: Build upload
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: android
            os: ubuntu-latest
            flutter_version: '3.4'
            flutter_channel: 'beta'
            artifact_name: release-apk
            artifact_path: build/app/outputs/apk/release/*.apk
          - target: ios
            os: macos-latest
            flutter_version: '3.3.4'
            flutter_channel: 'stable'
            artifact_name: release-ios
            artifact_path: build/**/*.ipa
#          - target: macos
#            os: macos-latest
#            flutter_version: '3.3.2'
#            artifact_name: release-mac
#            artifact_path: build/macos/*.zip
          - target: windows
            os: windows-2022
            flutter_version: '3.4'
            flutter_channel: 'beta'
            artifact_name: release-windows
            artifact_path: build/windows/*.zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Cache Flutter (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          path: /opt/hostedtoolcache/flutter
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Flutter (MacOS)
        if: matrix.os == 'macos-latest'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          path: /Users/runner/hostedtoolcache/flutter
          restore-keys: |
            ${{ runner.os }}-flutter-

      #      - name: Cache Flutter (Windows)
      #        if: matrix.os == 'windows-latest'
      #        uses: actions/cache@v3
      #        with:
      #          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
      #          path: 'C:\hostedtoolcache\windows\flutter'
      #          restore-keys: |
      #            ${{ runner.os }}-flutter-

      - name: Cache Gradle packages (Android)
        if: matrix.target == 'android'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Pods (build macos)
        uses: actions/cache@v3
        if: matrix.target == 'macos'
        with:
          path: |
            macos/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('macos/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Pods (build ios)
        uses: actions/cache@v3
        if: matrix.target == 'ios'
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-            


      - name: Decode keystore
        if: matrix.target == 'android'
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      # 安装 JDK
      - name: Setup Java JDK 11 (Android)
        if: matrix.target == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle

      # 安装 Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}
          channel: ${{ matrix.flutter_channel }}

      - name: Build resolve Swift dependencies
        if: matrix.os == 'macos-latest'
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Flutter pub get
        run: |
          git config --global core.longpaths true
          flutter pub get

      # Get app version
      - name: Get app version
        id: get_version
        shell: bash
        run: |
          echo "::set-output name=version::$(head -n 5 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2)"

      # 打包 apk
      - name: Collect Apks
        if: matrix.target == 'android'
        run: flutter build apk --release --split-per-abi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      # 打包 ipa
      - name: Build ios app
        if: matrix.target == 'ios'
        run: |
          cd ios && pod update && pod install && cd ..
          flutter build ios --release --no-codesign
      - name: Thin app
        if: matrix.target == 'ios'
        run: sh scripts/thin-payload.sh build/ios/iphoneos/*.app

      - name: Build ipa file
        if: matrix.target == 'ios'
        run: |
          cd build
          mkdir -p Payload
          mv ios/iphoneos/*.app Payload
          zip -9 Eros-N_${{ steps.get_version.outputs.version }}.ipa -r Payload

      # 打包 mac
      #      - name: Build mac app
      #        if: matrix.target == 'macos'
      #        run: |
      #          cd macos && pod update && pod install && cd ..
      #          flutter build macos --release
      #          APP_PATH=build/macos/Build/Products/Release/eros_n.app
      #          cp -a $APP_PATH ./build
      #          cd build && zip -qroy macos/Eros_N_macos.zip eros_n.app

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.target == 'windows'
        with:
          arch: x64
          sdk: 10.0.22621.0
          toolset: 14.33
          vsversion: 17.3.5
      - name: Build windows
        if: matrix.target == 'windows'
        run: |
          flutter build windows --release --verbose
          $DestDir = "build\windows\Eros_N"
          $SrcDir = "build\windows\runner\Release"
          New-Item -Path $DestDir -ItemType Directory
          Copy-Item $SrcDir\* -Recurse $DestDir
          Copy-Item -Filter *.dll -Path windows\* -Destination $DestDir -Force
          Compress-Archive $DestDir build\windows\Eros_N_windows_${{ steps.get_version.outputs.version }}.zip

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
